name: SURBER • US
description: "When <del>140</del> 280 characters just aren't enough"

avatar: http://j.mp/joshsurber
logo: http://j.mp/joshsurber
url: https://surber.us
baseurl: ""
permalink: /:year/:month/:title/
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :compressed # You might prefer to minify using :compressed

plugins:
- jekyll-browsersync
- jekyll-sitemap
- jekyll-feed
- jekyll-default-layout
- jekyll-titles-from-headings
# - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

titles_from_headings:
  enabled:     true
  strip_title: true
