name: Josh Surber
description: "World's Okayest Dad"

avatar: http://j.mp/joshsurber
logo: http://j.mp/joshsurber
url: https://surber.us
baseurl: ""
permalink: /:year/:month/:title/
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: surber

sass:
  style: :compressed # You might prefer to minify using :compressed

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-seo-tag
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

titles_from_headings:
  enabled: true
  strip_title: true

paginate: 5
